// client/fe/src/pages/LoginPage.vue
<script setup lang="ts">
import { ref, reactive } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Form, Input, Button, Card, message } from 'ant-design-vue'
import { UserOutlined, LockOutlined } from '@ant-design/icons-vue'
import { login } from '../api'
import { useAuthStore } from '../store/auth'

const router = useRouter()
const route = useRoute()
const authStore = useAuthStore()

const formRef = ref()
const loading = ref(false)
const formState = reactive({
  username: '',
  password: '',
})

const rules: Record<string, any> = {
  username: [{ required: true, message: '请输入用户名', trigger: 'blur' }],
  password: [{ required: true, message: '请输入密码', trigger: 'blur' }],
}

async function handleSubmit() {
  try {
    await formRef.value.validate()
    loading.value = true
    const res = await login({
      username: formState.username,
      password: formState.password,
    })
    const { token, uid } = res.data
    authStore.loginSuccess(token, uid, formState.username)
    message.success('登录成功')
    const redirect = (route.query.redirect as string) || '/products'
    router.push(redirect)
  } catch (err: any) {
    if (err?.response?.data?.message) {
      message.error(err.response.data.message)
    }
  } finally {
    loading.value = false
  }
}
</script>

<template>
  <div class="login-container">
    <Card class="login-card" :bordered="false">
      <h1 class="login-title">秒杀商城</h1>
      <p class="login-subtitle">IM 账号登录</p>

      <Form
        ref="formRef"
        :model="formState"
        :rules="rules"
        layout="vertical"
        @keyup.enter="handleSubmit"
      >
        <Form.Item name="username">
          <Input
            v-model:value="formState.username"
            size="large"
            placeholder="用户名"
            :prefix="UserOutlined"
          />
        </Form.Item>

        <Form.Item name="password">
          <Input.Password
            v-model:value="formState.password"
            size="large"
            placeholder="密码"
            :prefix="LockOutlined"
          />
        </Form.Item>

        <Form.Item>
          <Button
            type="primary"
            size="large"
            block
            :loading="loading"
            @click="handleSubmit"
          >
            登录
          </Button>
        </Form.Item>
      </Form>

      <div class="login-footer">
        还没有账号？
        <router-link to="/register">立即注册</router-link>
      </div>
    </Card>
  </div>
</template>

<style scoped>
.login-container {
  min-height: 100vh;
  display: flex;
  align-items: center;
  justify-content: center;
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
}

.login-card {
  width: 400px;
  border-radius: 12px;
  box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);
}

.login-title {
  text-align: center;
  font-size: 28px;
  font-weight: 700;
  color: #1a1a2e;
  margin-bottom: 4px;
}

.login-subtitle {
  text-align: center;
  color: #8c8c8c;
  margin-bottom: 32px;
  font-size: 14px;
}

.login-footer {
  text-align: center;
  color: #8c8c8c;
  font-size: 14px;
}

.login-footer a {
  color: #667eea;
  font-weight: 500;
}
</style>

// client/React/src/pages/LoginPage.tsx
import { useState } from 'react'
import { useNavigate, useSearchParams, Link } from 'react-router-dom'
import { Form, Input, Button, message, Typography } from 'antd'
import { UserOutlined, LockOutlined, ThunderboltOutlined } from '@ant-design/icons'
import { login, setBaseURL } from '../api'
import { useAuthStore } from '../store/auth'

export default function LoginPage() {
  const [loading, setLoading] = useState(false)
  const nav = useNavigate()
  const [params] = useSearchParams()
  const authStore = useAuthStore()

  const onFinish = async (v: { username: string; password: string }) => {
    setLoading(true)
    try {
      const res = await login(v)
      const { username, host, port, token, balance } = res.data
      authStore.loginSuccess(username, host, port, token, balance)
      setBaseURL(host, port)
      message.success(`欢迎 ${username}，登录成功！`, 1.5)
      nav(params.get('redirect') || '/products')
    } catch {} finally { setLoading(false) }
  }

  return (
    <div style={{ minHeight: 'calc(100vh - 56px)', background: 'linear-gradient(160deg, #0f0c29, #1a1a3e 30%, #24243e 60%, #1a1a3e)', display: 'flex', alignItems: 'center', justifyContent: 'center' }}>
      <div style={{ width: 420, padding: '48px 40px 40px', background: 'rgba(255,255,255,0.04)', backdropFilter: 'blur(24px)', border: '1px solid rgba(255,255,255,0.08)', borderRadius: 24 }}>
        <div style={{ textAlign: 'center', marginBottom: 36 }}>
          <div style={{ display: 'inline-flex', width: 56, height: 56, borderRadius: 16, background: 'linear-gradient(135deg,#667eea,#764ba2)', alignItems: 'center', justifyContent: 'center', fontSize: 28, color: '#fff', marginBottom: 16 }}><ThunderboltOutlined /></div>
          <h1 style={{ fontSize: 28, fontWeight: 800, color: '#fff', margin: '0 0 6px', letterSpacing: 2 }}>秒杀商城</h1>
          <Typography.Text style={{ color: 'rgba(255,255,255,0.45)' }}>登录 IM 账号，参与限时抢购</Typography.Text>
        </div>
        <Form onFinish={onFinish} size="large">
          <Form.Item name="username" rules={[{ required: true, message: '请输入用户名' }]}>
            <Input prefix={<UserOutlined />} placeholder="用户名" />
          </Form.Item>
          <Form.Item name="password" rules={[{ required: true, message: '请输入密码' }]}>
            <Input.Password prefix={<LockOutlined />} placeholder="密码" />
          </Form.Item>
          <Form.Item>
            <Button type="primary" htmlType="submit" loading={loading} block style={{ height: 48, borderRadius: 12, background: 'linear-gradient(135deg,#667eea,#764ba2)', border: 'none', fontWeight: 700, letterSpacing: 4 }}>登 录</Button>
          </Form.Item>
        </Form>
        <div style={{ textAlign: 'center', color: 'rgba(255,255,255,0.4)' }}>还没有账号？<Link to="/register" style={{ color: '#667eea', fontWeight: 600 }}>立即注册 →</Link></div>
      </div>
    </div>
  )
}
