// client/React/src/pages/RankPage.tsx
import { useEffect, useRef } from 'react'
import { useNavigate } from 'react-router-dom'
import { Button, Empty } from 'antd'
import { ArrowLeftOutlined, TrophyOutlined, FireOutlined } from '@ant-design/icons'
import { useProductStore } from '../store/product'

export default function RankPage() {
  const nav = useNavigate()
  const { rankList, fetchRank } = useProductStore()
  const timer = useRef<number>()

  useEffect(() => {
    fetchRank()
    timer.current = window.setInterval(fetchRank, 3000)
    return () => clearInterval(timer.current)
  }, [])

  return (
    <div style={{ minHeight: 'calc(100vh - 56px)', background: 'linear-gradient(160deg,#0f0c29,#1a1a3e 30%,#24243e 60%,#1a1a3e)', padding: 40, color: '#fff' }}>
      <div style={{ display: 'flex', alignItems: 'center', gap: 20, marginBottom: 32 }}>
        <Button type="text" icon={<ArrowLeftOutlined />} onClick={() => nav('/products')} style={{ color: 'rgba(255,255,255,0.5)' }}>返回商城</Button>
        <h1 style={{ fontSize: 24, margin: 0 }}><TrophyOutlined /> 抢购排行榜</h1>
      </div>
      {rankList.length === 0 ? <Empty description="暂无抢购数据" /> : (
        <ul style={{ listStyle: 'none', padding: 0, maxWidth: 600 }}>
          {rankList.map((item, idx) => (
            <li key={item.productId} style={{
              display: 'flex', alignItems: 'center', gap: 16, padding: '16px 20px',
              background: 'rgba(255,255,255,0.03)', border: `1px solid ${idx < 3 ? 'rgba(250,173,20,0.25)' : 'rgba(255,255,255,0.05)'}`,
              borderRadius: 12, marginBottom: 8,
            }}>
              <span style={{ fontSize: 18, fontWeight: 700, width: 40, textAlign: 'center' }}>{idx < 3 && <FireOutlined style={{ color: '#faad14' }} />} {idx + 1}</span>
              <span style={{ flex: 1, fontSize: 16 }}>{item.productName}</span>
              <span style={{ color: '#f5222d', fontWeight: 700 }}>{item.count} 件</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  )
}

// client/fe/src/pages/RankPage.vue
<script setup lang="ts">
import { onMounted, onUnmounted, ref } from 'vue'
import { Empty, Spin } from 'ant-design-vue'
import { TrophyOutlined, FireOutlined, ArrowLeftOutlined } from '@ant-design/icons-vue'
import { useRouter } from 'vue-router'
import { useProductStore } from '../store/product'

const router = useRouter()
const productStore = useProductStore()
const loading = ref(false)
let timer: number | null = null

onMounted(async () => {
  loading.value = true
  await productStore.fetchRank()
  loading.value = false
  timer = window.setInterval(async () => {
    await productStore.fetchRank()
  }, 3000)
})

onUnmounted(() => {
  if (timer) clearInterval(timer)
})
</script>

<template>
  <div class="rank-page">
    <header class="page-header">
      <span class="back-btn" @click="router.push('/products')">
        <ArrowLeftOutlined /> 返回商城
      </span>
      <h1><TrophyOutlined /> 抢购排行榜</h1>
    </header>
    <main>
      <Spin :spinning="loading">
        <Empty v-if="productStore.rankList.length === 0" description="暂无抢购数据" />
        <ul v-else class="rank-list">
          <li v-for="(item, idx) in productStore.rankList" :key="item.productId" class="rank-item" :class="{ 'top3': idx < 3 }">
            <span class="rank-idx">
              <FireOutlined v-if="idx < 3" />
              {{ idx + 1 }}
            </span>
            <span class="rank-name">{{ item.productName }}</span>
            <span class="rank-count">{{ item.count }} 件</span>
          </li>
        </ul>
      </Spin>
    </main>
  </div>
</template>

<style scoped>
.rank-page {
  min-height: calc(100vh - 56px);
  background: linear-gradient(160deg, #0f0c29 0%, #1a1a3e 30%, #24243e 60%, #1a1a3e 100%);
  padding: 40px; color: #fff;
}
.page-header {
  display: flex; align-items: center; gap: 20px; margin-bottom: 32px;
}
.back-btn { cursor: pointer; color: rgba(255,255,255,0.5); font-size: 14px; }
.back-btn:hover { color: #667eea; }
.page-header h1 { font-size: 24px; margin: 0; }
.rank-item {
  display: flex; align-items: center; gap: 16px; padding: 16px 20px;
  background: rgba(255,255,255,0.03); border: 1px solid rgba(255,255,255,0.05);
  border-radius: 12px; margin-bottom: 8px; max-width: 600px;
}
.rank-item.top3 { border-color: rgba(250,173,20,0.25); background: rgba(250,173,20,0.06); }
.rank-idx { font-size: 18px; font-weight: 700; width: 40px; text-align: center; }
.rank-name { flex: 1; font-size: 16px; }
.rank-count { color: #f5222d; font-weight: 700; }
</style>
